// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"github.com/Dorrrke/shortener-url-cource/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUser(s string) (models.User, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (models.User, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) models.User); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - s string
func (_e *MockUserRepository_Expecter) GetUser(s any) *MockUserRepository_GetUser_Call {
	return &MockUserRepository_GetUser_Call{Call: _e.mock.On("GetUser", s)}
}

func (_c *MockUserRepository_GetUser_Call) Run(run func(s string)) *MockUserRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUser_Call) Return(user models.User, err error) *MockUserRepository_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetUser_Call) RunAndReturn(run func(s string) (models.User, error)) *MockUserRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserInfo provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserInfo(s string) (models.User, []models.Link, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 models.User
	var r1 []models.Link
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (models.User, []models.Link, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) models.User); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(string) []models.Link); ok {
		r1 = returnFunc(s)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]models.Link)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(s)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserRepository_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type MockUserRepository_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - s string
func (_e *MockUserRepository_Expecter) GetUserInfo(s any) *MockUserRepository_GetUserInfo_Call {
	return &MockUserRepository_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", s)}
}

func (_c *MockUserRepository_GetUserInfo_Call) Run(run func(s string)) *MockUserRepository_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserInfo_Call) Return(user models.User, links []models.Link, err error) *MockUserRepository_GetUserInfo_Call {
	_c.Call.Return(user, links, err)
	return _c
}

func (_c *MockUserRepository_GetUserInfo_Call) RunAndReturn(run func(s string) (models.User, []models.Link, error)) *MockUserRepository_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) SaveUser(user models.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type MockUserRepository_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - user models.User
func (_e *MockUserRepository_Expecter) SaveUser(user any) *MockUserRepository_SaveUser_Call {
	return &MockUserRepository_SaveUser_Call{Call: _e.mock.On("SaveUser", user)}
}

func (_c *MockUserRepository_SaveUser_Call) Run(run func(user models.User)) *MockUserRepository_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.User
		if args[0] != nil {
			arg0 = args[0].(models.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_SaveUser_Call) Return(err error) *MockUserRepository_SaveUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_SaveUser_Call) RunAndReturn(run func(user models.User) error) *MockUserRepository_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}
