// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlers

import (
	"github.com/Dorrrke/shortener-url-cource/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLinkService creates a new instance of MockLinkService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkService {
	mock := &MockLinkService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLinkService is an autogenerated mock type for the LinkService type
type MockLinkService struct {
	mock.Mock
}

type MockLinkService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkService) EXPECT() *MockLinkService_Expecter {
	return &MockLinkService_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockLinkService
func (_mock *MockLinkService) Delete(s string) error {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLinkService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLinkService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - s string
func (_e *MockLinkService_Expecter) Delete(s any) *MockLinkService_Delete_Call {
	return &MockLinkService_Delete_Call{Call: _e.mock.On("Delete", s)}
}

func (_c *MockLinkService_Delete_Call) Run(run func(s string)) *MockLinkService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLinkService_Delete_Call) Return(err error) *MockLinkService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLinkService_Delete_Call) RunAndReturn(run func(s string) error) *MockLinkService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockLinkService
func (_mock *MockLinkService) Get(s string) (string, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockLinkService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - s string
func (_e *MockLinkService_Expecter) Get(s any) *MockLinkService_Get_Call {
	return &MockLinkService_Get_Call{Call: _e.mock.On("Get", s)}
}

func (_c *MockLinkService_Get_Call) Run(run func(s string)) *MockLinkService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLinkService_Get_Call) Return(s1 string, err error) *MockLinkService_Get_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *MockLinkService_Get_Call) RunAndReturn(run func(s string) (string, error)) *MockLinkService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockLinkService
func (_mock *MockLinkService) GetAll(s string) (map[string]models.Link, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]models.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (map[string]models.Link, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) map[string]models.Link); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]models.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockLinkService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - s string
func (_e *MockLinkService_Expecter) GetAll(s any) *MockLinkService_GetAll_Call {
	return &MockLinkService_GetAll_Call{Call: _e.mock.On("GetAll", s)}
}

func (_c *MockLinkService_GetAll_Call) Run(run func(s string)) *MockLinkService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLinkService_GetAll_Call) Return(stringToLink map[string]models.Link, err error) *MockLinkService_GetAll_Call {
	_c.Call.Return(stringToLink, err)
	return _c
}

func (_c *MockLinkService_GetAll_Call) RunAndReturn(run func(s string) (map[string]models.Link, error)) *MockLinkService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// SaveURL provides a mock function for the type MockLinkService
func (_mock *MockLinkService) SaveURL(s string, s1 string) (string, error) {
	ret := _mock.Called(s, s1)

	if len(ret) == 0 {
		panic("no return value specified for SaveURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(s, s1)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkService_SaveURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveURL'
type MockLinkService_SaveURL_Call struct {
	*mock.Call
}

// SaveURL is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *MockLinkService_Expecter) SaveURL(s any, s1 any) *MockLinkService_SaveURL_Call {
	return &MockLinkService_SaveURL_Call{Call: _e.mock.On("SaveURL", s, s1)}
}

func (_c *MockLinkService_SaveURL_Call) Run(run func(s string, s1 string)) *MockLinkService_SaveURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLinkService_SaveURL_Call) Return(s2 string, err error) *MockLinkService_SaveURL_Call {
	_c.Call.Return(s2, err)
	return _c
}

func (_c *MockLinkService_SaveURL_Call) RunAndReturn(run func(s string, s1 string) (string, error)) *MockLinkService_SaveURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// GetUserInfo provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUserInfo(s string) (models.UserInfo, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 models.UserInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (models.UserInfo, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) models.UserInfo); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(models.UserInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type MockUserService_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - s string
func (_e *MockUserService_Expecter) GetUserInfo(s any) *MockUserService_GetUserInfo_Call {
	return &MockUserService_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", s)}
}

func (_c *MockUserService_GetUserInfo_Call) Run(run func(s string)) *MockUserService_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_GetUserInfo_Call) Return(userInfo models.UserInfo, err error) *MockUserService_GetUserInfo_Call {
	_c.Call.Return(userInfo, err)
	return _c
}

func (_c *MockUserService_GetUserInfo_Call) RunAndReturn(run func(s string) (models.UserInfo, error)) *MockUserService_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUser provides a mock function for the type MockUserService
func (_mock *MockUserService) SaveUser(registerRequest models.RegisterRequest) (string, error) {
	ret := _mock.Called(registerRequest)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.RegisterRequest) (string, error)); ok {
		return returnFunc(registerRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(models.RegisterRequest) string); ok {
		r0 = returnFunc(registerRequest)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(models.RegisterRequest) error); ok {
		r1 = returnFunc(registerRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type MockUserService_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - registerRequest models.RegisterRequest
func (_e *MockUserService_Expecter) SaveUser(registerRequest any) *MockUserService_SaveUser_Call {
	return &MockUserService_SaveUser_Call{Call: _e.mock.On("SaveUser", registerRequest)}
}

func (_c *MockUserService_SaveUser_Call) Run(run func(registerRequest models.RegisterRequest)) *MockUserService_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.RegisterRequest
		if args[0] != nil {
			arg0 = args[0].(models.RegisterRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_SaveUser_Call) Return(s string, err error) *MockUserService_SaveUser_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserService_SaveUser_Call) RunAndReturn(run func(registerRequest models.RegisterRequest) (string, error)) *MockUserService_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}

// ValidationUser provides a mock function for the type MockUserService
func (_mock *MockUserService) ValidationUser(loginRequest models.LoginRequest) (string, error) {
	ret := _mock.Called(loginRequest)

	if len(ret) == 0 {
		panic("no return value specified for ValidationUser")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(models.LoginRequest) (string, error)); ok {
		return returnFunc(loginRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(models.LoginRequest) string); ok {
		r0 = returnFunc(loginRequest)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(models.LoginRequest) error); ok {
		r1 = returnFunc(loginRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_ValidationUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidationUser'
type MockUserService_ValidationUser_Call struct {
	*mock.Call
}

// ValidationUser is a helper method to define mock.On call
//   - loginRequest models.LoginRequest
func (_e *MockUserService_Expecter) ValidationUser(loginRequest any) *MockUserService_ValidationUser_Call {
	return &MockUserService_ValidationUser_Call{Call: _e.mock.On("ValidationUser", loginRequest)}
}

func (_c *MockUserService_ValidationUser_Call) Run(run func(loginRequest models.LoginRequest)) *MockUserService_ValidationUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.LoginRequest
		if args[0] != nil {
			arg0 = args[0].(models.LoginRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserService_ValidationUser_Call) Return(s string, err error) *MockUserService_ValidationUser_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserService_ValidationUser_Call) RunAndReturn(run func(loginRequest models.LoginRequest) (string, error)) *MockUserService_ValidationUser_Call {
	_c.Call.Return(run)
	return _c
}
