// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"github.com/Dorrrke/shortener-url-cource/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLinkRepository creates a new instance of MockLinkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLinkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLinkRepository {
	mock := &MockLinkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLinkRepository is an autogenerated mock type for the LinkRepository type
type MockLinkRepository struct {
	mock.Mock
}

type MockLinkRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLinkRepository) EXPECT() *MockLinkRepository_Expecter {
	return &MockLinkRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) Delete(s string) error {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLinkRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockLinkRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - s string
func (_e *MockLinkRepository_Expecter) Delete(s any) *MockLinkRepository_Delete_Call {
	return &MockLinkRepository_Delete_Call{Call: _e.mock.On("Delete", s)}
}

func (_c *MockLinkRepository_Delete_Call) Run(run func(s string)) *MockLinkRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLinkRepository_Delete_Call) Return(err error) *MockLinkRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLinkRepository_Delete_Call) RunAndReturn(run func(s string) error) *MockLinkRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) Get(s string) (string, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockLinkRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - s string
func (_e *MockLinkRepository_Expecter) Get(s any) *MockLinkRepository_Get_Call {
	return &MockLinkRepository_Get_Call{Call: _e.mock.On("Get", s)}
}

func (_c *MockLinkRepository_Get_Call) Run(run func(s string)) *MockLinkRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLinkRepository_Get_Call) Return(s1 string, err error) *MockLinkRepository_Get_Call {
	_c.Call.Return(s1, err)
	return _c
}

func (_c *MockLinkRepository_Get_Call) RunAndReturn(run func(s string) (string, error)) *MockLinkRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) GetAll(s string) (map[string]models.Link, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 map[string]models.Link
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (map[string]models.Link, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) map[string]models.Link); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]models.Link)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLinkRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockLinkRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - s string
func (_e *MockLinkRepository_Expecter) GetAll(s any) *MockLinkRepository_GetAll_Call {
	return &MockLinkRepository_GetAll_Call{Call: _e.mock.On("GetAll", s)}
}

func (_c *MockLinkRepository_GetAll_Call) Run(run func(s string)) *MockLinkRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLinkRepository_GetAll_Call) Return(stringToLink map[string]models.Link, err error) *MockLinkRepository_GetAll_Call {
	_c.Call.Return(stringToLink, err)
	return _c
}

func (_c *MockLinkRepository_GetAll_Call) RunAndReturn(run func(s string) (map[string]models.Link, error)) *MockLinkRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockLinkRepository
func (_mock *MockLinkRepository) Save(link models.Link) error {
	ret := _mock.Called(link)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.Link) error); ok {
		r0 = returnFunc(link)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLinkRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockLinkRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - link models.Link
func (_e *MockLinkRepository_Expecter) Save(link any) *MockLinkRepository_Save_Call {
	return &MockLinkRepository_Save_Call{Call: _e.mock.On("Save", link)}
}

func (_c *MockLinkRepository_Save_Call) Run(run func(link models.Link)) *MockLinkRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.Link
		if args[0] != nil {
			arg0 = args[0].(models.Link)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockLinkRepository_Save_Call) Return(err error) *MockLinkRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLinkRepository_Save_Call) RunAndReturn(run func(link models.Link) error) *MockLinkRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
